apiVersion: apps/v1
kind: Deployment
metadata:
  name: storefront
  namespace: default
  labels:
    mycompany.com/policy-version: "2.2.0"
    department: engineering
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storefront
  template:
    metadata:
      labels:
        app: storefront
        mycompany.com/policy-version: "2.2.0"
        department: engineering
    spec:
      containers:
        - name: storefront
          image: ghcr.io/policy-as-versioned-flux/storefront@sha256:dd36bd84218259814d245bf6430aa80b866e06186e15a524fb6e592675e78b4d # v1.0.0
          ports:
            - containerPort: 80
