apiVersion: apps/v1
kind: Deployment
metadata:
  name: storefront
  namespace: default
  labels:
    mycompany.com/policy-version: "2.2.0"
    department: engineering
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storefront
  template:
    metadata:
      labels:
        app: storefront
        mycompany.com/policy-version: "2.2.0"
        department: engineering
    spec:
      containers:
        - name: storefront
          image: ghcr.io/policy-as-versioned-flux/storefront@sha256:ef53f41d380af4f56aa3e1f1e4ad922fa64e8f47361a41e83822fa8ace0f96bc # v1.0.0
          ports:
            - containerPort: 80
